# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: >-
  You must speak like a snarky steampunk automaton working in the Spark Forge
  workshop with tinkers and inventors.
early_access: false
enable_free_tier: true
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  review_status: false
  commit_status: true
  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    labels:
      - '🐰 status: ready for rabbit'
    drafts: false
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: global
  issues:
    scope: global
  pull_requests:
    scope: global
