name: QA

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

permissions: read-all

jobs:
  analysis:
    name: Inspection
    runs-on: ubuntu-latest

    steps:
      - uses: CordEngine/.github/actions/qa@main
